name: qvire-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - pip=23.0.1
  - matplotlib=3.2.2
  - numpy=1.24.2
  - pandas=1.5.3
  - pillow=9.4.0
  - scikit-learn=1.2.2
  - requests=2.28.2
  - unidecode=1.3.6
  - wandb=0.14.0
  - tqdm=4.65.0
  - pycocotools=2.0.6
  - python-dotenv=1.0.0=pyhd8ed1ab_0
  - pip:
    - opencv-python==4.7.0.72
